language: node_js
node_js:
- 9
sudo: required
script:
- npm install
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: rV85cGLJRvW7sg5XNnkMumTWH51M/b6XtUnMyKu4IEN8CjwH+/gVyRAjgpoNAcmloGi/DECk4Yv2l0DvrhrBkwE+a/vFz074UwLrjHXMHZ8D3un+sTjfpvvdG2n8HwbSSTJ298diHvLXxkeoDZxyD3W1kGTeA/j2e7s1aV2rLl0BFMi/gLmjVmKvx2CRJXZYP4zg2OqpMpK7ZcdvTt0zzXzupAI5kuzP4YgERMq2I1cPjrJJ/oZL4rtWKBxFiQoxeuoRZSsPGCGQd0TDRXJ7OSH0dMiwPSoDG6xsIzaTtqylI+dt6SvcNui6mC96Etolv9NlWoEJSga6jNx7L+lwCugpiCpZMfHCXGpkPdnyeSSkcU+PA+JFQ5xl9uI5XWZhWcB/qWIoz06duzOUi7DAKkPZS2cWP5Nw25KeB67Ic6hKyEc+Y+7DEZGDEiRM/ANfkAO60SOWNjhIebwN9VRJ5Vw2JAnCBo71sdtfBMAfmm2BH4YhZaTa054zSsCVfUW3LkRoDKqlXFvueyNXhB7XQrxZ7JmagYt1dFnWUrWVZUKHrY2y4+Jo28iRY0OiycnezzYieU3ZXvtJcZLPibu1vIr2pNSXb6LRDu9Js6bapCYhQQYhd8JTes1RMnJ72v/kOD7YPDfVz3DvAsQ7hHRR/mASLNq7XCT6bI5dyqw+c48=
  secret_access_key:
    secure: e82wIBvKV2Wy9M847B1fKxYpyEhTVtyD/ig8m4U++4wkc5+7ckywIkjwx5Bq5ZLWaJGr9tpwJFRRcrIgEAmc+eqTI9wWAbXzC4FA5HFN+mw8LRhbMTdbG9JqhA+zIs5pOvkrPkS+2fVA8v8q5ZUMSKYXfh2ov7hq9J1c8TwpBcRnSsjIzXYpmCcQ1/plvri5YVUC6zV9x2ZdvliIZhGDTNbtVDfnfkUMSNJG8V0cktAb3yNtO+Bs2yT3SnrJhkWE1KcZmNT/09y3aDDOOHvXOurZKIwiLj3FI3GoUfJAKdTmG2TUaXUDBLAbubRdPFgre7Nuvs42X1qUNzxgt+vWeQxgu4WSLgw91H7YZGqMx09oxAPCytveq7TFHwqffKwcfKGfAMIyDt8FYPVNqweLaiXEqYu6qDLP7alVx3FMUTQ7nMWPSgVaAwwV/zIv+OtAaILsfESEr4Ba17E8pmWGFFgt5wr86xSJJKOl78n1gszA+UleJ+KhKZNHccQYwSAyls1T2rGZzDUesu0ENK9RtXKFCePZv6Hn85q9Qr4XWzZ+JtaDto8Z03o6g2RnvKWklxKSDg3keVArr0+0cOdvhBrjqXHRhXsCfEMzMNoABa4znGZhUc4+QQi35NXs9pHlnd6YENZVE47Oe6bN5AMyAj1g/Nqb3BDW3c2bNOWmZvg=
  region: us-west-2
  bucket: danielhawton.info
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: dhawton/resume
    branch: master
