language: node_js
node_js:
- 9
sudo: required
script:
- npm install
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: t4XgSASftjVoZ09yDJS1Z2QbIfBOvrNTN+FRC1VafTEwf/G6DseZf5ow6NzUsr9JOgy7xtnuPawmF7Y/kex764zZSDWcfYI6NfdMfBQujGBMdanscVi48DusNkpJaMHyeClr1XT5CmqKjG5190/VG6NXaXV/5l33KsCuV2A6EUyLylfNl3lzFY5k/4ij6DOVXHeuS3r00A89wTsS9lL+sJZ4m7H8QNI1td82izB+0igO1eMntGi26tOo5rhfsLGgZmgv4ZRVQlY53aXqbAbZMYHNqzVGhrtYnx5rX29eWgkaEFvFcx+MQg6FqeQXbIIKmo8vOLz52FSSkq3Z2oaRbWnZEN2vNGgJr286kMZMHcj50TKMd0ONF1fHSsGdfUqLX0TFoToHLQNlM1iirFEa9KVZnD/BI+sCvqEdUfHxNkFdRSBn5kKKv/X6BmA8Q0jWp4wA4AXkXoTc+AYsevrTvOxJNXI+/2Wn63K2db3TQSxoqBbZ3wBIkdM1Mcs5rO6qxmQBSV4z3P/seXEjyOTE6Kft9kq3ozhLttTuIDQaJhArhpRhtZrffv/tnB+paoxqRHkEEmG6SdrpVPw3qjNndGg03I5i9tX+sA8ZcAqmRGrTn/GtIAoEUiPPKmT3TjPtGTtqe+ZXpDGjKryEocvfMLnm/2IgRk/U1rdhboEq0tU=
  secret_access_key:
    secure: VaKu5IVNiUhDoo3EuMDVWV/B/tIVps8a+Zplk8TQIOgsJ0Eq4TdqEz9QDIPU2Qtz875jDzxGzfzvqz9CKhzlN2kzc7/Ewx7Fo5RsttnOuSJojNthILzRsqqJU2xcPGa63fg4imnGzqEVIf8rwlxmYKyCbvCtIVnsAoz+z8R5Ok6I58bz+FeqUdtFC+kG5zxPgCi/2kmgKQW4xqRlGUOiHWBlm6l1kOeOsewLvWhNGic7agKFx0W+cAKBTCM8zNekYit2xdBxBge7nHp6l+17bajb0+afNvwes8znBqMFJBrExdyZLZtMfPNo3ESwC2nk0WkeUoj4pmse/C+8qN4egkpnx98lebh1qieLAb0Y3W1O+c9S4PSwogZy8mEvsHw2aNKa9k0rQkPd82gYnRnRGeMkVNcvAwSWLenbhVERWyM6M4P0cpwx+hSwRwJMuucIU/f/o+4uZCGxwsdFB1vpV89qOsosgCpCYXf+AGBAkZQJvefbCl7Co5jZQZhIiNIe0H+8hC8roXVf9z7i3B1QoCxERIXmIhv4utfXhtcVvOCttf3NEaNwASoRdUOsfOJ8wPVDClWX+Fq3qs8qPjJSi/fG4scv7hr6YxsxsHpruA/U5UyeZYym9F9RJd137zr2eNuVnT2kKony0Fk5fDY4jJNtn2jC4Y6qSSk/tASfb7E=
  region: us-west-2
  bucket: danielhawton.info
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: dhawton/resume
    branch: master
